spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/smart_booking_db}
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Sql2005}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port = 8081
spring.jackson.serialization.write-dates-as-timestamps=false

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=navadeeponline@gmail.com
spring.mail.password=hanofpxnjpvlhxso
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true